"""changing Foreign Key

Revision ID: 763e126937da
Revises: 
Create Date: 2023-10-12 21:16:25.391818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763e126937da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'types_of_devices', ['device_type'], ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'types_of_devices', ['device_type'], ['name'])
    # ### end Alembic commands ###
